image:
  repository: ghcr.io/muchobien/pocketbase
  tag: latest

resources:
  requests:
    memory: 32Mi
    cpu: 10m
  limits:
    memory: 150Mi
    cpu: 200m

persistence:
  data:
    enabled: true
    existingClaim: pvc-pocketbase-data

env:
  TZ: America/Sao_Paulo
