apiVersion: apps/v1
kind: Deployment
metadata:
  name: umami
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umami
  template:
    metadata:
      labels:
        app: umami
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.35
          command: ["sh", "-c", "until nc -z postgres-shared.core.svc.cluster.local 5432; do echo 'Aguardando postgres-shared...'; sleep 5; done"]
      containers:
        - name: umami
          image: ghcr.io/umami-software/umami:postgresql-latest
          ports:
            - containerPort: 3000
          env:
            - name: TZ
              value: America/Sao_Paulo
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: DATABASE_URL
              value: "postgresql://postgres:$(DB_PASS)@postgres-shared.core.svc.cluster.local:5432/umami"
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/heartbeat
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/heartbeat
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: umami
  namespace: monitoring
spec:
  selector:
    app: umami
  ports:
    - port: 3000
      targetPort: 3000