apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/tank-hd/nexus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: development
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeName: nexus-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          env:
            - name: INSTALL4J_ADD_VM_PARAMS
              value: "-Xms1g -Xmx1g -XX:MaxDirectMemorySize=2g"
          ports:
            - name: ui
              containerPort: 8081
            - name: docker
              containerPort: 5000
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
            - name: nexus-tmp
              mountPath: /tmp
          resources:
            requests:
              memory: 2Gi
              cpu: 250m
            limits:
              memory: 4Gi
              cpu: 2
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pvc
        - name: nexus-tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: development
spec:
  selector:
    app: nexus
  ports:
    - name: ui
      port: 8081
      targetPort: 8081
    - name: docker
      port: 5000
      targetPort: 5000

