apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          ports:
            - containerPort: 8191
          env:
            - name: TZ
              value: America/Sao_Paulo
            - name: LOG_LEVEL
              value: info
            - name: LOG_HTML
              value: "false"
            - name: CAPTCHA_SOLVER
              value: none
            - name: BROWSER_TIMEOUT
              value: "70000"
            - name: MAX_TIMEOUT
              value: "120000"
            - name: SESSION_TIMEOUT
              value: "300"
            - name: CHROME_ARGS
              value: --disable-dev-shm-usage,--disable-gpu,--no-sandbox,--disable-extensions,--disable-background-networking,--disable-sync,--metrics-recording-only,--disable-default-apps,--no-first-run
          resources:
            requests:
              memory: 256Mi
              cpu: 50m
            limits:
              memory: 700Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: media
spec:
  selector:
    app: flaresolverr
  ports:
    - port: 8191
      targetPort: 8191
