apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-secret
  namespace: monitoring
spec:
  encryptedData:
    PGADMIN_DEFAULT_EMAIL: AgCk2M9apGxpVoDMJj1ePAZFrruT8ueHBwwyRQh0l2SIzDoUIuse5QQqbGkVQpVzqOcYjSHULGNh189bH1S/6UYGMMXEO0yKX0Mwt8SuRLnETcLjdzQJVxcaBRsbektS2CiOkIC0QGBzxeqJSSCH28vVE42YnzEsnmXc8WqUZo2fW8BuG6khf0Wn5pYBS3dLr3jRfFAh3P3JGadgPsotTjg7bDrLxTEeiCulNjNcFrDIcL09JCAc/JLMqCepccrFfqGMaybllGxx7cJYJ0TWTc9iIZ3edQDcNBmaXXxmBr4grDh5hYOA0qA5SpAFgtG32NRzrZyuJixUmjXzK8f9QW5KZyOZ0cmx6JrURzSlq5VGedJmwNmxvBRRNTKouduT+pm1iad2XJ7mX0sSb1OFLYFs6fEJ7ZzQl2Mt3JFD4ihECt6q2LuoFMDf1m0K9oqNGGveaAePeHa6yxHho9cWYcVCgt4tkhH//dA23sr7SF9dM6qjqDs1gvBfK1ljN7gdBBDMjLy4NG37CTpLa2PSNSy8mIOuljD1HjDu3Wn0JH94tcmZozQuCRN1IkGXsCJq4C6e4SgiS5jM8Rge+5puTAANhfcZ869SBpPltkcocUBm81fFpo7MqHcWMXSpExsQaB/FalzF5rBhP6wVsLrkzAVJJ/VUEstdpIVV7AgZXKEEMq7DC4BDfhaV4g9cRIfMRrOwI83csOpFnDN7wo7P9mHadhxhk0fMXZwoTWHA3Sk2pg4HpNSf
    PGADMIN_DEFAULT_PASSWORD: AgBGn7Hfi8o6Pt6tKlft2yDUUjT4S/kX2cMXS1ExlzQz6qfKb59htoif/kFvCsgD51qd2msgu2HIzrcPM9LdUg2iniOwmTCedDG97/E91MMm/UvXWvkv6VcZO4R4fe9IVX8EPgn77/aS1W1O6fxypTE/pu4yxEKpM9ZfO4w575g0sfJ2xN5uFhTnby6940jazeQ7SePma3wIU0geyvz8lL4wnYpZw+zC8R69z5Ba4a2KfvcdFvhHlCTM32Qjd6BiKXYedTyrVFCmCTtYw6gXLCKFcDaWiYVXxF5tU5PZ3EqwTYi+QIg+LZcbaOPLllnv1ZGuI5T3WkEFtXM7r8DdnjscE55/xnpzdfdMk1ri+AjVUj81dXiNUD4rhy6sPE+bCgsCtGQrm/gBZmNr9GZFDIoZYXwVk0wLMJ6Xgw/gnwm/JPa8C3mZNMMq6DP5pZwS01ds2e7TFyXrJxP2MmoSPZNK7LZMdj9/VOSf0VJi/xT7+2Um0biToPNT3FcDfDA/v7I7ce+fFLQF5sETBJPSEJh8s9D8jGGqMLN0nE77B9s6aPXbhXqrvZdngAj1uk9hCFNrrWd9y2DRbbdv2P3xVqo4Ck6UvY1aCmG76GRk6lkZCfFPkSjiFmzfKcJMpkDdHdC8GySNqFwneQmkHjt/haM30Whp8K7Pn3/oRIVyaQ523N18tEwc3yvTG0XzeoAB8Hd/qbu6GY6PKAxvjqBGs6LJD6gYo2Mc5sk=
  template:
    metadata:
      name: pgadmin-secret
      namespace: monitoring
    type: Opaque
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  hostPath:
    path: /mnt/seagate-2tb/pgadmin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ''
  volumeName: pgadmin-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: monitoring
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      securityContext:
        runAsUser: 5050
        runAsGroup: 5050
        fsGroup: 5050
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:9.16
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: pgadmin-secret
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
          livenessProbe:
            httpGet:
              path: /misc/ping
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /misc/ping
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 3
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgadmin
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pgadmin-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: monitoring
spec:
  selector:
    app: pgadmin
  ports:
    - name: http
      port: 80
      targetPort: 80
