apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: monitoring
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 10m
        memory: 64Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: core
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 10m
        memory: 64Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: media
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 50m
        memory: 128Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: security
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 10m
        memory: 64Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: development
spec:
  limits:
    - type: Container
      default:
        cpu: 300m
        memory: 512Mi
      defaultRequest:
        cpu: 20m
        memory: 128Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: immich
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 50m
        memory: 128Mi
