# ==================
# CORE
# ==================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  namespace: core
spec:
  storageClassName: storage-ext
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis
  namespace: core
spec:
  storageClassName: storage-ext
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-config
  namespace: core
spec:
  storageClassName: storage-ext
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cloudflared-config
  namespace: core
spec:
  storageClassName: storage-ext
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wikijs-data
  namespace: core
spec:
  storageClassName: tank-hd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pocketbase-data
  namespace: core
spec:
  storageClassName: tank-hd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-umami-data
  namespace: core
spec:
  storageClassName: tank-hd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# ==================
# MEDIA
# ==================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-big-storage
  namespace: media
spec:
  storageClassName: big-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1700Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin-config
  namespace: media
spec:
  storageClassName: storage-ext
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-radarr-config
  namespace: media
spec:
  storageClassName: storage-ext
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarr-config
  namespace: media
spec:
  storageClassName: storage-ext
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prowlarr-config
  namespace: media
spec:
  storageClassName: storage-ext
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-bazarr-config
  namespace: media
spec:
  storageClassName: storage-ext
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-seerr-config
  namespace: media
spec:
  storageClassName: storage-ext
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-qbittorrent-config
  namespace: media
spec:
  storageClassName: storage-ext
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-fileflows-config
  namespace: media
spec:
  storageClassName: storage-ext
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# ==================
# IMMICH
# ==================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich-media
  namespace: immich
spec:
  storageClassName: big-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1700Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich-config
  namespace: immich
spec:
  storageClassName: storage-ext
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# ==================
# MONITORING
# ==================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-netdata-config
  namespace: monitoring
spec:
  storageClassName: tank-hd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-netdata-lib
  namespace: monitoring
spec:
  storageClassName: tank-hd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-uptime-kuma
  namespace: monitoring
spec:
  storageClassName: tank-hd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# ==================
# SECURITY
# ==================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-authentik-media
  namespace: security
spec:
  storageClassName: storage-ext
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# ==================
# DEVELOPMENT
# ==================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins-data
  namespace: development
spec:
  storageClassName: tank-hd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
