apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: big-storage
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  nodePath: /mnt/big_storage
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-ext
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  nodePath: /mnt/storage_ext
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tank-hd
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  nodePath: /mnt/tank-hd
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ext-ssh-bk
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  nodePath: /mnt/ext_ssh_bk
