apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
  namespace: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      hostNetwork: false
      containers:
        - name: adguard
          image: adguard/adguardhome:latest
          ports:
            - containerPort: 3000
              name: setup
            - containerPort: 80
              name: http
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
              hostPort: 53
            - containerPort: 53
              name: dns-udp
              protocol: UDP
              hostPort: 53
          env:
            - name: TZ
              value: America/Sao_Paulo
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 456Mi
              cpu: 200m
          volumeMounts:
            - name: data
              mountPath: /opt/adguardhome/work
            - name: config
              mountPath: /opt/adguardhome/conf
      volumes:
        - name: data
          hostPath:
            path: /mnt/tank-hd/adguard/work
            type: DirectoryOrCreate
        - name: config
          hostPath:
            path: /mnt/tank-hd/adguard/conf
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: adguard
  namespace: core
spec:
  selector:
    app: adguard
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: setup
      port: 3000
      targetPort: 3000