apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: consul-secret
  namespace: development
spec:
  encryptedData:
    CONSUL_LOCAL_CONFIG: AgB9f3zyj/eAJWdKjSYohfe3d5MHPDliPxDmYd4yOm31Y5NJxmo2Fis4qGKWetOUTXD+2jZFcW7FHg4ZGEtXpHGJq4KSuB8iNvQtmP9mbviclxWTE7RrL2kB2r+zf3JZQZZqiDJYSnQ+RQslYlyZoT9WASmLSpbTo+gK6XRs18i3wt1lNbFHEgR/aRW6g0cwjooTqPkKnYKbN23mBF9lnTc5rWTQbAOarCL/DYFMQ8PZtmtbMjXbrqARHnnXzzRgoYLuzxpiHMEv2Uc8fo3cyMBOZYlhEspGuvR7kqbbGg7YV8jDzxEj/kyLLVT7+Jqik4aAWQLdCkTbYZX+zFoKz/Lux2M3Cj/n0/n+Ip1OLBRAwc/luvAT41Bu/h7rFeXjolE6jaDVXhnieXbsE8uEzP2o10EixkYhJpamQB9be0mEP7nB449GUgFH0lpqSbkNusH0PPMniK8aNCievAdWfuh4cTx2p5OTG5QUMtyzCgGihfGf/UHFhAqwSbBpEMUzUygNDB7WbIb6bqh6OC0j6/nue60zn8h8VTZud7qvuIR6VxamW9qytZ267PCCn+Qyp4aMv+3mW8aCCNjx3X27O9R1iZpxxyYFGm07y1m293+cnelTT/Gs7Cv9YPR5hZZQGLWu467sOF49gdV63DmAtuRNCgtwBuF8e/cXyPCZpSYnsAaD4E3cjLFeDnOAOGuSSYBh32E05W0bmmjyabfYv/y8qMOO81vJz+SjkKqAPfktPpuxWqUSAJnz+P4vgUlhhtRRr+bAdV9TDnPEjjXgoMw+3bGXWQo7FO9eT9Cy7VkrWvrrV/aPaaPst+csh1o2c0YtuBCqlERbr1JmiQ7pvPZIrag4k63cGXbuq75Ot7VZhrr04fRHx5d5Vly7pJHWROluJHmIUXQMSM+VAr1QBOqwu99I891mjCnueBaOTt8aA3J1DcK/0qlPvVGrsRn0DcHNVxZkEAXmt+iYI7w9L2k0Ao9nSv0eVTNJ12BXQtqV43mfx7cDaKeNyFzWE0i1/FryveA4H+Mp2F2o7FY00z+HV3QKPkDw1huLFHplNeF7JTw0SqAFLvNTxLzwajFX6hQDlT4wIpnoQMXot4QZIOJ9F7M/L3Pa+5cJl2fWsJrQuR35U38Y3AnBPXxxv7pOXA+QktFB3F3ATIkvzOXc5r75Hdyu3kZ/Wlvwb3MNzU9GuglRikT2i7S7uNJNFcb4F+k0b2wX9wNKipQ8WvqEJH9lXpoIjn+FTbPz+puddoXkN2+eH972kRr3BjMuudxFfUhhnMiUAd5VwKbBlEb2NMN+K/bK2/PCHBf+GKsDJF101YoUEluBADMhDrGYjeFZijIkwSt65L5rsQU2w+wBuVejMcRE9220KO8OHxhY
  template:
    metadata:
      name: consul-secret
      namespace: development
    type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: hashicorp/consul:1.22.7
          ports:
            - containerPort: 8500
              name: http
            - containerPort: 8600
              name: dns
              protocol: UDP
          env:
            - name: TZ
              value: America/Sao_Paulo
            - name: GOGC
              value: "80"
            - name: CONSUL_LOCAL_CONFIG
              valueFrom:
                secretKeyRef:
                  name: consul-secret
                  key: CONSUL_LOCAL_CONFIG
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /v1/status/leader
              port: 8500
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /v1/status/leader
              port: 8500
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 3
          volumeMounts:
            - name: data
              mountPath: /consul/data
      volumes:
        - name: data
          hostPath:
            path: /mnt/seagate-2tb/consul
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: development
spec:
  selector:
    app: consul
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: dns
      port: 8600
      targetPort: 8600
      protocol: UDP
