image:
  repository: louislam/uptime-kuma
  tag: latest

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 250Mi
    cpu: 500m

persistence:
  data:
    enabled: true
    existingClaim: pvc-uptime-kuma

env:
  TZ: America/Sao_Paulo
