apiVersion: apps/v1
kind: Deployment
metadata:
  name: netdata
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netdata
  template:
    metadata:
      labels:
        app: netdata
    spec:
      hostNetwork: false
      hostPID: true
      containers:
        - name: netdata
          image: netdata/netdata:latest
          ports:
            - containerPort: 19999
          env:
            - name: TZ
              value: America/Sao_Paulo
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 750Mi
              cpu: 150m
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
                - SYS_ADMIN
          volumeMounts:
            - name: config
              mountPath: /etc/netdata
            - name: lib
              mountPath: /var/lib/netdata
            - name: cache
              mountPath: /var/cache/netdata
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: docker-sock
              mountPath: /var/run/docker.sock
              readOnly: true
      volumes:
        - name: config
          hostPath:
            path: /mnt/storage_ext/netdata/config
            type: DirectoryOrCreate
        - name: lib
          hostPath:
            path: /mnt/storage_ext/netdata/lib
            type: DirectoryOrCreate
        - name: cache
          hostPath:
            path: /mnt/storage_ext/netdata/cache
            type: DirectoryOrCreate
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: netdata
  namespace: monitoring
spec:
  selector:
    app: netdata
  ports:
    - port: 19999
      targetPort: 19999