apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileflows
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fileflows
  template:
    metadata:
      labels:
        app: fileflows
    spec:
      runtimeClassName: nvidia
      securityContext:
        supplementalGroups:
          - 44
          - 992
      containers:
        - name: fileflows
          image: revenz/fileflows:latest

          env:
            - name: TZ
              value: America/Sao_Paulo
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"

            # 🔥 GPU
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: compute,video,utility

            - name: MACHINE_LEARNING_DEVICE
              value: cuda

          resources:
            limits:
              nvidia.com/gpu: 1

          volumeMounts:
            # ffmpeg do host
            - name: ffmpeg
              mountPath: /usr/bin/ffmpeg
              readOnly: true
            - name: ffprobe
              mountPath: /usr/bin/ffprobe
              readOnly: true

      volumes:
        - name: ffmpeg
          hostPath:
            path: /usr/bin/ffmpeg
            type: File
        - name: ffprobe
          hostPath:
            path: /usr/bin/ffprobe
            type: File
