apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seerr
  template:
    metadata:
      labels:
        app: seerr
    spec:
      initContainers:
        - name: init
          image: busybox
          command: ['sh', '-c', 'chown -R 1000:1000 /app/config']
          volumeMounts:
            - name: config
              mountPath: /app/config
      containers:
        - name: seerr
          image: ghcr.io/seerr-team/seerr:sha-8d351bc
          ports:
            - containerPort: 5055
          env:
            - name: TZ
              value: America/Sao_Paulo
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: 5055
            initialDelaySeconds: 60   
            timeoutSeconds: 10        
            periodSeconds: 30        
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: 5055
            initialDelaySeconds: 30  
            timeoutSeconds: 5      
            periodSeconds: 10
            failureThreshold: 6       
          startupProbe:             
            httpGet:
              path: /api/v1/status
              port: 5055
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          hostPath:
            path: /mnt/ext_ssh_bk/configs/seerr
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: seerr
  namespace: media
spec:
  selector:
    app: seerr
  ports:
    - port: 5055
      targetPort: 5055
