apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seerr
  template:
    metadata:
      labels:
        app: seerr
    spec:
      initContainers:
        - name: init
          image: busybox
          command: ['sh', '-c', 'chown -R 1000:1000 /app/config']
          volumeMounts:
            - name: config
              mountPath: /app/config
      containers:
        - name: seerr
          image: ghcr.io/seerr-team/seerr:latest
          ports:
            - containerPort: 5055
          env:
            - name: TZ
              value: America/Sao_Paulo
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 525Mi
              cpu: 200m
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: 5055
            initialDelaySeconds: 20
            timeoutSeconds: 3
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:           # ← adiciona isso
            httpGet:
              path: /api/v1/status
              port: 5055
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 2
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          hostPath:
            path: /mnt/ext_ssh_bk/configs/seerr
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: seerr
  namespace: media
spec:
  selector:
    app: seerr
  ports:
    - port: 5055
      targetPort: 5055