apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-shared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Felipeb26/HomeServer.git
    targetRevision: HEAD
    path: charts/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-shared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Felipeb26/HomeServer.git
    targetRevision: HEAD
    path: charts/redis
  destination:
    server: https://kubernetes.default.svc
    namespace: core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Felipeb26/HomeServer.git
    targetRevision: HEAD
    path: charts/cloudflared
  destination:
    server: https://kubernetes.default.svc
    namespace: core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebrowser
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Felipeb26/HomeServer.git
    targetRevision: HEAD
    path: charts/filebrowser
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Felipeb26/HomeServer.git
    targetRevision: HEAD
    path: charts/adguard
  destination:
    server: https://kubernetes.default.svc
    namespace: core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gotify
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Felipeb26/HomeServer.git
    targetRevision: HEAD
    path: charts/gotify
  destination:
    server: https://kubernetes.default.svc
    namespace: core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
