apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: core
data:
  init-databases.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
      CREATE DATABASE immich;
      CREATE DATABASE umami;
      CREATE DATABASE authentik;
      CREATE DATABASE wikijs;
    EOSQL