image:
  repository: tensorchord/pgvecto-rs
  tag: pg14-v0.2.0

primary:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 2Gi
      cpu: 1000m

  persistence:
    enabled: true
    existingClaim: pvc-postgres

  configuration: |
    shared_buffers = 512MB
    effective_cache_size = 1536MB
    work_mem = 32MB
    max_connections = 100

auth:
  existingSecret: postgres-secret
